openapi: 3.0.1
info:
  title: API di Upload Immagine
  version: 1.0.0
paths:
  /images/upload:
    post:
      summary: Carica un'immagine e restituisce l'id dell'immagine caricata
      operationId: uploadImage
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                files:
                  type: array
                  items:
                    type: string
                    format: binary
                  maxItems: 5
      responses:
        "200":
          description: Id immagini
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: long
                      description: ID del file salvato nel database
                    nome:
                      type: string
                      description: Nome originale del file
                    url:
                      type: string
                      description: URL pubblico del file salvato